/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package footballmanager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author wesker
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Java Football Manager");
        wor.IniciarKolin();
        
    }
    
    
    int IndexContinente = 999;
    int IndexLiga = 999;
    int IndexEquipo = 999;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ligs = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ekipes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Ekipis = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Java Football Manager");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escoge tu continente");

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("America");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Europa");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 51));
        jButton3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Asia");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Escoge liga");

        Ligs.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(Ligs);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Escoge equipo");

        Ekipes.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(Ekipes);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Equipo seleccionado:");

        Ekipis.setEditable(false);
        Ekipis.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jButton4.setBackground(new java.awt.Color(0, 153, 51));
        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Iniciar");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 51));
        jButton5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Am. Norte centro");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ekipis, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1)
                        .addGap(48, 48, 48)
                        .addComponent(jButton2)
                        .addGap(49, 49, 49)
                        .addComponent(jButton3)
                        .addGap(42, 42, 42)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Ekipis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IndexContinente = 0;
        RenderizarContinentesLigas("America");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        IndexContinente = 1;
        RenderizarContinentesLigas("Europa");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        IndexContinente = 2;
        RenderizarContinentesLigas("Asia");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if (IndexContinente==999 && IndexLiga==999 && IndexEquipo==999 && NombreEquipo!=""){
            System.out.println("NONEEES ");
        }else{
        
        
        
        wor.EleccionPlayer(IndexContinente,IndexLiga,NombreEquipo);
        
        
        VistaEquipo vis = new VistaEquipo(wor);
        
        vis.setVisible(true);
        
        this.dispose();
        
        
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        IndexContinente = 3;
        RenderizarContinentesLigas("America norte centro");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    Mundo wor = new Mundo(2024);
    
    String NombreEquipo = "";
   
    
    public void RenderizarEquipos(String Continente,int IndexLigs){
        switch (Continente){
            case "America" ->{
                int Indis = 0;
                for (Equipo ekipe : wor.LigasAmerica.get(IndexLigs).Equipos){
                    
                    JButton ds = new JButton();
                    ds.setBackground(new java.awt.Color(0,102,51));
                    ds.setForeground(new java.awt.Color(255,255,255));
                    ds.setFont(new java.awt.Font("Arial", 0, 24));
                    ds.setText(ekipe.NombreEquipo);
                    int Indlers = Indis;
                    ds.addActionListener((ActionEvent f)->{
                    IndexContinente = 0;
                    IndexLiga = IndexLigs;
                    IndexEquipo = Indlers;
                               
                    Ekipis.setText(ekipe.NombreEquipo+"("+wor.LigasAmerica.get(IndexLigs).NombreLiga+")");
                    NombreEquipo = ekipe.NombreEquipo;           
                    });
                    
                    Ekipes.add(ds);
                    
                    
                    Indis++;
                }
            }
            case "America norte centro"->{
                int Indis = 0;
                for (Equipo ekipe : wor.LigasAmericanortecentro.get(IndexLigs).Equipos){
                    
                    JButton ds = new JButton();
                    ds.setBackground(new java.awt.Color(0,102,51));
                    ds.setForeground(new java.awt.Color(255,255,255));
                    ds.setFont(new java.awt.Font("Arial", 0, 24));
                    ds.setText(ekipe.NombreEquipo);
                    int Indlers = Indis;
                    ds.addActionListener((ActionEvent f)->{
                    IndexContinente = 3;
                    IndexLiga = IndexLigs;
                    IndexEquipo = Indlers;
                               
                    Ekipis.setText(ekipe.NombreEquipo+"("+wor.LigasAmericanortecentro.get(IndexLigs).NombreLiga+")");
                    NombreEquipo = ekipe.NombreEquipo;           
                    });
                    
                    Ekipes.add(ds);
                    
                    
                    Indis++;
                }
            }
            case "Europa" ->{
                int Indis = 0;
                for (Equipo ekipe : wor.LigasEuropa.get(IndexLigs).Equipos){
                    
                    JButton ds = new JButton();
                    ds.setBackground(new java.awt.Color(0,102,51));
                    ds.setForeground(new java.awt.Color(255,255,255));
                    ds.setFont(new java.awt.Font("Arial", 0, 24));
                    ds.setText(ekipe.NombreEquipo);
                    int Indlers = Indis;
                    ds.addActionListener((ActionEvent f)->{
                    IndexContinente = 1;
                    IndexLiga = IndexLigs;
                    IndexEquipo = Indlers;
                               
                    Ekipis.setText(ekipe.NombreEquipo+"("+wor.LigasEuropa.get(IndexLigs).NombreLiga+")");
                    NombreEquipo = ekipe.NombreEquipo;           
                    });
                    
                    Ekipes.add(ds);
                    
                    
                    Indis++;
                }
            
            }
            case "Asia" ->{
                int Indis = 0;
                for (Equipo ekipe : wor.LigasAsia.get(IndexLigs).Equipos){
                    
                    JButton ds = new JButton();
                    ds.setBackground(new java.awt.Color(0,102,51));
                    ds.setForeground(new java.awt.Color(255,255,255));
                    ds.setFont(new java.awt.Font("Arial", 0, 24));
                    ds.setText(ekipe.NombreEquipo);
                    int Indlers = Indis;
                    ds.addActionListener((ActionEvent f)->{
                    IndexContinente = 2;
                    IndexLiga = IndexLigs;
                    IndexEquipo = Indlers;
                               
                    Ekipis.setText(ekipe.NombreEquipo+"("+wor.LigasAsia.get(IndexLigs).NombreLiga+")");
                    NombreEquipo = ekipe.NombreEquipo;           
                    });
                    
                    Ekipes.add(ds);
                    
                    
                    Indis++;
                }
            
            }
        }
    }
    
    
    
    public void RenderizarContinentesLigas(String WichOne){
        Ligs.removeAll();
        Ekipes.removeAll();
        switch (WichOne){
            case "America"->{
                for (int i = 0 ; i<wor.LigasAmerica.size();i++){
                    int Indix = i;
                    JButton nut = new JButton();
                   nut.setBackground(new java.awt.Color(0,102,51));
                   nut.setForeground(new java.awt.Color(255,255,255));
                   nut.setFont(new java.awt.Font("Arial", 0, 24));
                   nut.setText(wor.LigasAmerica.get(i).NombreLiga);
                   nut.addActionListener((ActionEvent e) -> {
                       IndexContinente = 0;
                       Ekipes.removeAll();
                       IndexLiga = Indix;
                       RenderizarEquipos("America",Indix);
                       Ekipes.updateUI();
                       
                    });
                   
                 Ligs.add(nut);
                 
                }
                Ligs.updateUI();
                Ekipes.updateUI();
            }
            case "Europa" ->{
                for (int i = 0 ; i<wor.LigasEuropa.size();i++){
                    int Indix = i;
                    JButton nut = new JButton();
                   nut.setBackground(new java.awt.Color(0,102,51));
                   nut.setForeground(new java.awt.Color(255,255,255));
                   nut.setFont(new java.awt.Font("Arial", 0, 24));
                   nut.setText(wor.LigasEuropa.get(i).NombreLiga);
                   nut.addActionListener((ActionEvent e) -> {
                       IndexContinente = 1;
                       Ekipes.removeAll();
                       IndexLiga = Indix;
                       RenderizarEquipos("Europa",Indix);
                       Ekipes.updateUI();
                       
                    });
                   
                 Ligs.add(nut);
                 
                }
                Ligs.updateUI();
                Ekipes.updateUI();
            
            }
            case "Asia"->{
                for (int i = 0 ; i<wor.LigasAsia.size();i++){
                    int Indix = i;
                    JButton nut = new JButton();
                   nut.setBackground(new java.awt.Color(0,102,51));
                   nut.setForeground(new java.awt.Color(255,255,255));
                   nut.setFont(new java.awt.Font("Arial", 0, 24));
                   nut.setText(wor.LigasAsia.get(i).NombreLiga);
                   nut.addActionListener((ActionEvent e) -> {
                       IndexContinente = 2;
                       Ekipes.removeAll();
                       IndexLiga = Indix;
                       RenderizarEquipos("Asia",Indix);
                       Ekipes.updateUI();
                       
                    });
                   
                 Ligs.add(nut);
                 
                }
                Ligs.updateUI();
                Ekipes.updateUI();
            
            }
            case "America norte centro"->{
                for (int i = 0 ; i<wor.LigasAmericanortecentro.size();i++){
                    int Indix = i;
                    JButton nut = new JButton();
                   nut.setBackground(new java.awt.Color(0,102,51));
                   nut.setForeground(new java.awt.Color(255,255,255));
                   nut.setFont(new java.awt.Font("Arial", 0, 24));
                   nut.setText(wor.LigasAmericanortecentro.get(i).NombreLiga);
                   nut.addActionListener((ActionEvent e) -> {
                       IndexContinente = 3;
                       Ekipes.removeAll();
                       IndexLiga = Indix;
                       RenderizarEquipos("America norte centro",Indix);
                       Ekipes.updateUI();
                       
                    });
                   
                 Ligs.add(nut);
                 
                }
                Ligs.updateUI();
                Ekipes.updateUI();
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ekipes;
    private javax.swing.JTextField Ekipis;
    private javax.swing.JPanel Ligs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
