/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package footballmanager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author wesker
 */
public class VistaPlantel extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     * @param wor
     */
    public VistaPlantel(Mundo wor) {
        initComponents();
        this.wor = wor;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Java Football Manager");
 
        this.RenderizarVista();
    }

    
    //0 es onceinicial 1 es reserva
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NombreEquipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OnceInicial = new javax.swing.JPanel();
        Avanzar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Jugador2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        EntRestantes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        NombreJug = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Salary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Rest = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        Ataque = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        Edad1 = new javax.swing.JLabel();
        Atac = new javax.swing.JTextField();
        Atac1 = new javax.swing.JTextField();
        Ataque1 = new javax.swing.JLabel();
        Atac2 = new javax.swing.JTextField();
        Ataque2 = new javax.swing.JLabel();
        Atac3 = new javax.swing.JTextField();
        Ataque3 = new javax.swing.JLabel();
        Ataque4 = new javax.swing.JLabel();
        Ataque5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Reservas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        NombreEquipo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        NombreEquipo.setForeground(new java.awt.Color(255, 255, 255));
        NombreEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEquipo.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Once inicial");

        OnceInicial.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(OnceInicial);

        Avanzar.setBackground(new java.awt.Color(0, 204, 102));
        Avanzar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Avanzar.setForeground(new java.awt.Color(255, 255, 255));
        Avanzar.setText("Volver al menú anterior");
        Avanzar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanzarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Banca");

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Opciones Equipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cambio de jugador");

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Cambiar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Jugador2.setEditable(false);
        Jugador2.setBackground(new java.awt.Color(153, 255, 153));
        Jugador2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Jugador2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton2.setText("Entrenar equipo");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EntRestantes.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EntRestantes.setForeground(new java.awt.Color(255, 255, 255));
        EntRestantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EntRestantes.setText("Entrenamientos restantes:0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(354, 354, 354))
                    .addComponent(EntRestantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntRestantes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Futbolista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        NombreJug.setEditable(false);
        NombreJug.setBackground(new java.awt.Color(153, 255, 153));
        NombreJug.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        NombreJug.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreJug.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setText("Renovar contrato");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setText("Vender jugador");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton5.setText("Liberar jugador");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton6.setText("Preguntarle sobre retiro");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contrato");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Año de contratación:");

        Salary.setEditable(false);
        Salary.setBackground(new java.awt.Color(153, 255, 153));
        Salary.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Salary.setText("$");
        Salary.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Salario por temporada");

        Rest.setEditable(false);
        Rest.setBackground(new java.awt.Color(153, 255, 153));
        Rest.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Rest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Rest.setText("$");
        Rest.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Temporadas restantes de contrato");

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton7.setText("Asignar dorsal");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        Ataque.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ataque.setForeground(new java.awt.Color(255, 255, 255));
        Ataque.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Ataque.setText("Ataque:");

        Valor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 255, 255));
        Valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Valor.setText("Valor:");

        Edad1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Edad1.setForeground(new java.awt.Color(255, 255, 255));
        Edad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Edad1.setText("Edad");

        Atac.setEditable(false);
        Atac.setBackground(new java.awt.Color(153, 255, 153));
        Atac.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Atac.setText("0");

        Atac1.setEditable(false);
        Atac1.setBackground(new java.awt.Color(153, 255, 153));
        Atac1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Atac1.setText("0");

        Ataque1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ataque1.setForeground(new java.awt.Color(255, 255, 255));
        Ataque1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Ataque1.setText("Mediocampo:");

        Atac2.setEditable(false);
        Atac2.setBackground(new java.awt.Color(153, 255, 153));
        Atac2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Atac2.setText("0");

        Ataque2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ataque2.setForeground(new java.awt.Color(255, 255, 255));
        Ataque2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Ataque2.setText("Defensa:");

        Atac3.setEditable(false);
        Atac3.setBackground(new java.awt.Color(153, 255, 153));
        Atac3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Atac3.setText("0");

        Ataque3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ataque3.setForeground(new java.awt.Color(255, 255, 255));
        Ataque3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Ataque3.setText("Porteria:");

        Ataque4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ataque4.setForeground(new java.awt.Color(255, 255, 255));
        Ataque4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ataque4.setText("Media:");

        Ataque5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ataque5.setForeground(new java.awt.Color(255, 255, 255));
        Ataque5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ataque5.setText("Dorsal:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ataque4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombreJug)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salary)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rest)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(Valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Ataque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Atac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Ataque1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Atac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ataque2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Atac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Ataque3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Atac3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Ataque5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreJug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Edad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ataque3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ataque)
                        .addComponent(Atac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Atac3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ataque2)
                        .addComponent(Atac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ataque1)
                        .addComponent(Atac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ataque5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ataque4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        Reservas.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(Reservas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NombreEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(Avanzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Avanzar)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanzarActionPerformed
        // TODO add your handling code here:
        VistaEquipo vivi = new VistaEquipo(wor);
        
        vivi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AvanzarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Eleccion!=3 && IndexJug!=999){
            switch (Eleccion){
                case 0 ->{
                    String[] Opciones = {"Cambiar jugador","Arrepentirse"};
                    JComboBox opciones = new JComboBox(getJugadoresLista(1));
                    int IndexCambio = JOptionPane.showOptionDialog(null, opciones,"Elige el jugador",JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,Opciones,
                Opciones[0]);
                    
                    if (IndexCambio == 0){
                    
                    if (wor.getEquipoPlayer().OnceInicial.get(IndexJug).Posicion.equals("Arquero") && !wor.getEquipoPlayer().Reserva.get(opciones.getSelectedIndex()).Posicion.equals("Arquero")){
                        JOptionPane.showMessageDialog(null, 
                              "Al cambiar el arquero debes hacerlo por otro arquero!!", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
                    }else{
                        wor.getEquipoPlayer().CambioJugador(IndexJug, opciones.getSelectedIndex());
                        RenderizarVista();
                        Eleccion = 3;
                        IndexJug = 999;
                        clearFields();
                    }
                    }
                }
                case 1 ->{
                    String[] Opciones = {"Cambiar jugador","Arrepentirse"};
                    JComboBox opciones = new JComboBox(getJugadoresLista(0));
                    int IndexCambio = JOptionPane.showOptionDialog(null, opciones,"Elige el jugador",JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,Opciones,
                Opciones[0]);
                    if (IndexCambio == 0){
                    if (wor.getEquipoPlayer().Reserva.get(IndexJug).Posicion.equals("Arquero") && !wor.getEquipoPlayer().OnceInicial.get(opciones.getSelectedIndex()).Posicion.equals("Arquero")){
                        JOptionPane.showMessageDialog(null, 
                              "Al cambiar el arquero debes hacerlo por otro arquero!!", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
                    }else{
                        wor.getEquipoPlayer().CambioJugador(opciones.getSelectedIndex(), IndexJug);
                        RenderizarVista();
                        Eleccion = 3;
                        IndexJug = 999;
                        clearFields();
                    }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        wor.getEquipoPlayer().entrenarPlantel();
        clearFields();
        RenderizarVista();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (Eleccion!=3 && IndexJug!=999){
            switch (Eleccion){
                case 0 ->{
                    wor.getEquipoPlayer().OnceInicial.get(IndexJug).respuestaSobreRetiro();
                }
                case 1 ->{
                    wor.getEquipoPlayer().Reserva.get(IndexJug).respuestaSobreRetiro();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, 
                              "No has seleccionado a ningun jugador", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (Eleccion!=3 && IndexJug!=999){
        
        wor.getEquipoPlayer().AsignarDorsal(Eleccion, IndexJug);
        clearFields();
        RenderizarVista();
        
        }else{
            JOptionPane.showMessageDialog(null, 
                              "No has seleccionado a ningun jugador", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         if (Eleccion!=3 && IndexJug!=999){
        
            if (Eleccion==1){
                if (wor.getEquipoPlayer().liberarJugador(wor, IndexJug)==true){
                    clearFields();
                    RenderizarVista();
                }
            }else{
                JOptionPane.showMessageDialog(null, 
                              "Para liberar a un jugador tiene que estar en reservas!", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
            }
        
        }else{
            JOptionPane.showMessageDialog(null, 
                              "No has seleccionado a ningun jugador", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (Eleccion!=3 && IndexJug!=333){
            VistaRenovarContrato Gu = new VistaRenovarContrato(wor,Eleccion,IndexJug);
            Gu.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, 
                              "No has seleccionado a ningun jugador", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public String[] getJugadoresLista(int Elecc){
        switch (Elecc){
            case 0 ->{
                ArrayList<String> Jugadores = new ArrayList<>();
                
                for (Futbolista nomb : wor.getEquipoPlayer().OnceInicial){
                    Jugadores.add(nomb.Nombre+" "+nomb.Apellido+"("+nomb.Posicion+")");
                }
                return Jugadores.toArray(String[]::new);
            }
            case 1 ->{
                ArrayList<String> Jugadores = new ArrayList<>();
                
                for (Futbolista nomb : wor.getEquipoPlayer().Reserva){
                    Jugadores.add(nomb.Nombre+" "+nomb.Apellido+"("+nomb.Posicion+")");
                }
                return Jugadores.toArray(String[]::new);
            }
        }
        return null;
    }
    
    Mundo wor;
    
    // 0 onceciniail 1 reserva
    int Eleccion = 3;
    
    // uindex jufg 
    int IndexJug = 999;
    
    
    public void AjustarGagrit(Futbolista x){
        NombreJug.setText(x.Nombre+" "+x.Apellido+"("+x.Posicion+")");
        Edad1.setText("Edad:"+x.Edad);
        Atac.setText(String.valueOf(x.Tiro));
        Atac1.setText(String.valueOf(x.Pase));
        Atac2.setText(String.valueOf(x.Defensa));
        Atac3.setText(String.valueOf(x.Porteria));
        Ataque4.setText("Media:"+x.Media);
        Valor.setText("Valor:$"+x.Precio);
        Ataque5.setText("Dorsal:"+x.Dorsal);
        Salary.setText("$"+x.ContratoJugador.SalarioPorTemporada);
        Rest.setText(String.valueOf(x.ContratoJugador.TemporadasContrato));
        jLabel5.setText("Año de contratación:"+x.ContratoJugador.AgnoContratado);
    }
    
    public void clearFields(){
        NombreJug.setText("");
        Edad1.setText("Edad");
        Atac.setText("0");
        Atac1.setText("0");
        Atac2.setText("0");
        Atac3.setText("0");
        Ataque4.setText("Media");
        Valor.setText("Valor");
        Ataque5.setText("Dorsal");
        Salary.setText("$");
        Rest.setText("");
        jLabel5.setText("Año de contratación");
    }
    
    public void RenderizarVista(){
        NombreEquipo.setText(wor.getEquipoPlayer().NombreEquipo);
        
        Eleccion = 3;
        IndexJug = 999;
        Jugador2.setText("");
        
        OnceInicial.removeAll();
        
        int Indies = 0;
        
        for (Futbolista x : wor.getEquipoPlayer().OnceInicial){
            VistaJugador vivi = new VistaJugador();
            vivi.Ajustar(x);
            int Indos = Indies;
             MouseListener ml = new MouseAdapter(){
                    
                    @Override
                    public void mousePressed(MouseEvent e){
                        Eleccion = 0;
                        IndexJug = Indos;
                        
                        Jugador2.setText(x.Nombre+" "+x.Apellido+"("+x.Posicion+")");
                        AjustarGagrit(x);
                    }
                };
                vivi.addMouseListener(ml);
            Indies++;
            OnceInicial.add(vivi);
        }
        Indies = 0;
        Reservas.removeAll();
        for (Futbolista y : wor.getEquipoPlayer().Reserva){
            VistaJugador vivi = new VistaJugador();
            vivi.Ajustar(y);
            
            int Indos = Indies;
             MouseListener ml = new MouseAdapter(){
                    
                    @Override
                    public void mousePressed(MouseEvent e){
                        Eleccion = 1;
                        IndexJug = Indos;
                        
                        Jugador2.setText(y.Nombre+" "+y.Apellido+"("+y.Posicion+")");
                        AjustarGagrit(y);
                    }
                };
                vivi.addMouseListener(ml);
            Indies++;
            OnceInicial.add(vivi);
            
            
            
            Reservas.add(vivi);
        }
        
        EntRestantes.setText("Entrenamientos restantes:"+wor.getEquipoPlayer().EntrenosPorEquipo);
      
        OnceInicial.updateUI();
        Reservas.updateUI();
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Atac;
    private javax.swing.JTextField Atac1;
    private javax.swing.JTextField Atac2;
    private javax.swing.JTextField Atac3;
    private javax.swing.JLabel Ataque;
    private javax.swing.JLabel Ataque1;
    private javax.swing.JLabel Ataque2;
    private javax.swing.JLabel Ataque3;
    private javax.swing.JLabel Ataque4;
    private javax.swing.JLabel Ataque5;
    private javax.swing.JButton Avanzar;
    private javax.swing.JLabel Edad1;
    private javax.swing.JLabel EntRestantes;
    private javax.swing.JTextField Jugador2;
    private javax.swing.JLabel NombreEquipo;
    private javax.swing.JTextField NombreJug;
    private javax.swing.JPanel OnceInicial;
    private javax.swing.JPanel Reservas;
    private javax.swing.JTextField Rest;
    private javax.swing.JTextField Salary;
    private javax.swing.JLabel Valor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
