/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package footballmanager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author wesker
 */
public class VistaEquipo extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     * @param wor
     */
    public VistaEquipo(Mundo wor) {
        initComponents();
        this.wor = wor;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Java Football Manager");
 
        this.RenderizarVista();
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NombreEquipo = new javax.swing.JLabel();
        Plantel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Fans = new javax.swing.JLabel();
        Capa = new javax.swing.JLabel();
        Ataque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Medio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Dfe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Porte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Forma = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Punt = new javax.swing.JTextField();
        Pg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Pp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Pe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Ga = new javax.swing.JTextField();
        Ge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Temp = new javax.swing.JLabel();
        TablaPos = new javax.swing.JButton();
        Avanzar = new javax.swing.JButton();
        Fich = new javax.swing.JButton();
        Trofe = new javax.swing.JButton();
        Mejoras = new javax.swing.JButton();
        RetirarJug = new javax.swing.JButton();
        Fondos = new javax.swing.JLabel();
        RetirarJug1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Results = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        NombreEquipo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        NombreEquipo.setForeground(new java.awt.Color(255, 255, 255));
        NombreEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEquipo.setText("jLabel1");

        Plantel.setBackground(new java.awt.Color(0, 204, 102));
        Plantel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Plantel.setForeground(new java.awt.Color(255, 255, 255));
        Plantel.setText("Ver plantel");
        Plantel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Plantel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resultados");

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "INFORMACIÓN EQUIPO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        Fans.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Fans.setForeground(new java.awt.Color(255, 255, 255));
        Fans.setText("Fans:");

        Capa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Capa.setForeground(new java.awt.Color(255, 255, 255));
        Capa.setText("Cap. Estadio:");

        Ataque.setEditable(false);
        Ataque.setBackground(new java.awt.Color(153, 255, 153));
        Ataque.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ataque.setText("100.00");
        Ataque.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ataque:");

        Medio.setEditable(false);
        Medio.setBackground(new java.awt.Color(153, 255, 153));
        Medio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Medio.setText("100.00");
        Medio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mediocampo:");

        Dfe.setEditable(false);
        Dfe.setBackground(new java.awt.Color(153, 255, 153));
        Dfe.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Dfe.setText("100.00");
        Dfe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Defensa:");

        Porte.setEditable(false);
        Porte.setBackground(new java.awt.Color(153, 255, 153));
        Porte.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Porte.setText("100.00");
        Porte.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Porteria:");

        Forma.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Forma.setForeground(new java.awt.Color(255, 255, 255));
        Forma.setText("Formacion:");

        Edad.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Edad.setForeground(new java.awt.Color(255, 255, 255));
        Edad.setText("Edad media:");

        Valor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 255, 255));
        Valor.setText("Valor total del plantel:$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Fans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Capa, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                                    .addComponent(Forma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ataque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Medio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Porte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dfe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fans)
                            .addComponent(Ataque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Capa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Forma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Edad))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Medio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Dfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Porte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Valor)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "EST. LIGA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Puntos:");

        Punt.setEditable(false);
        Punt.setBackground(new java.awt.Color(153, 255, 153));
        Punt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Punt.setText("0");
        Punt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Pg.setEditable(false);
        Pg.setBackground(new java.awt.Color(153, 255, 153));
        Pg.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pg.setText("0");
        Pg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Partidos ganados:");

        Pp.setEditable(false);
        Pp.setBackground(new java.awt.Color(153, 255, 153));
        Pp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pp.setText("0");
        Pp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Partidos perdidos:");

        Pe.setEditable(false);
        Pe.setBackground(new java.awt.Color(153, 255, 153));
        Pe.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pe.setText("0");
        Pe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Partidos empatados:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Goles Ant.");

        Ga.setEditable(false);
        Ga.setBackground(new java.awt.Color(153, 255, 153));
        Ga.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ga.setText("0");
        Ga.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Ge.setEditable(false);
        Ge.setBackground(new java.awt.Color(153, 255, 153));
        Ge.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ge.setText("0");
        Ge.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Goles Ec.");

        Temp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Temp.setForeground(new java.awt.Color(255, 255, 255));
        Temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Temp.setText("Temporada 2020-2020");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Temp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Punt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Pg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(Ga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Pp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Ge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Pe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Temp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Punt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TablaPos.setBackground(new java.awt.Color(0, 204, 102));
        TablaPos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        TablaPos.setForeground(new java.awt.Color(255, 255, 255));
        TablaPos.setText("Tabla de posiciones (nombreliga)");
        TablaPos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TablaPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablaPosActionPerformed(evt);
            }
        });

        Avanzar.setBackground(new java.awt.Color(0, 204, 102));
        Avanzar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Avanzar.setForeground(new java.awt.Color(255, 255, 255));
        Avanzar.setText("Avanzar");
        Avanzar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanzarActionPerformed(evt);
            }
        });

        Fich.setBackground(new java.awt.Color(0, 204, 102));
        Fich.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Fich.setForeground(new java.awt.Color(255, 255, 255));
        Fich.setText("Fichar jugadores");
        Fich.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Trofe.setBackground(new java.awt.Color(0, 204, 102));
        Trofe.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Trofe.setForeground(new java.awt.Color(255, 255, 255));
        Trofe.setText("Vitrina de trofeos");
        Trofe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Trofe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrofeActionPerformed(evt);
            }
        });

        Mejoras.setBackground(new java.awt.Color(0, 204, 102));
        Mejoras.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Mejoras.setForeground(new java.awt.Color(255, 255, 255));
        Mejoras.setText("Mejoras");
        Mejoras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RetirarJug.setBackground(new java.awt.Color(0, 204, 102));
        RetirarJug.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        RetirarJug.setForeground(new java.awt.Color(255, 255, 255));
        RetirarJug.setText("Retirar jugador/Sellar leyenda");
        RetirarJug.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Fondos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Fondos.setForeground(new java.awt.Color(255, 255, 255));
        Fondos.setText("Fondos:$");

        RetirarJug1.setBackground(new java.awt.Color(0, 204, 102));
        RetirarJug1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        RetirarJug1.setForeground(new java.awt.Color(255, 255, 255));
        RetirarJug1.setText("Finanzas Equipo");
        RetirarJug1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RetirarJug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarJug1ActionPerformed(evt);
            }
        });

        Results.setEditable(false);
        Results.setBackground(new java.awt.Color(255, 255, 255));
        Results.setColumns(20);
        Results.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Results.setRows(5);
        jScrollPane1.setViewportView(Results);

        jComboBox1.setBackground(new java.awt.Color(153, 255, 153));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liga" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Plantel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TablaPos, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Fich)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mejoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Trofe))
                                    .addComponent(RetirarJug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RetirarJug1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Fondos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(Avanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreEquipo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Plantel)
                            .addComponent(TablaPos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fich)
                            .addComponent(Trofe)
                            .addComponent(Mejoras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RetirarJug1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RetirarJug)
                        .addGap(114, 114, 114)
                        .addComponent(Fondos)
                        .addGap(100, 100, 100)
                        .addComponent(Avanzar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlantelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantelActionPerformed
        // TODO add your handling code here:
        
        VistaPlantel Vistis = new VistaPlantel(wor);
        Vistis.setVisible(true);
        
        this.dispose();

    }//GEN-LAST:event_PlantelActionPerformed

    private void TablaPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablaPosActionPerformed
        // TODO add your handling code here:
        VistaTabla vivi = new VistaTabla(wor,wor.getLigaPlayer());
        
        vivi.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_TablaPosActionPerformed

    private void RetirarJug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarJug1ActionPerformed
        // TODO add your handling code here:
        VistaFinanzasEquipo Fifa = new VistaFinanzasEquipo(wor);
        Fifa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RetirarJug1ActionPerformed

    private void AvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanzarActionPerformed
        // TODO add your handling code here:
        wor.AvanzarSemana(this);
        RenderizarVista();
    }//GEN-LAST:event_AvanzarActionPerformed

    private void TrofeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrofeActionPerformed
        // TODO add your handling code here:
        
        if (!wor.getEquipoPlayer().Trofeos.isEmpty()){
        
        
        String Trofies = "";
                
        for (Trofeo x : wor.getEquipoPlayer().Trofeos){
                    Trofies+="\n"+x.NombreTrofeo+"\n";
        }
                
        JOptionPane.showMessageDialog(null, 
              Trofies, 
              "Trofeos de "+wor.getEquipoPlayer().NombreEquipo, 
               JOptionPane.INFORMATION_MESSAGE);
        
        }else{
            JOptionPane.showMessageDialog(null, 
              "Aun no tienes trofeos", 
              "Vitrina vacía", 
               JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TrofeActionPerformed

    
    
    Mundo wor;


    public void RenderizarVista(){
        NombreEquipo.setText(wor.getEquipoPlayer().NombreEquipo);
        Fans.setText("Fans:"+wor.getEquipoPlayer().Fans);
        Capa.setText("Cap. Estadio:"+wor.getEquipoPlayer().EstEquipo.Capacidad);
        Forma.setText("Formacion:"+wor.getEquipoPlayer().getFormacion());
        Edad.setText("Edad media:"+wor.getEquipoPlayer().getEdadMedia());
        Valor.setText("Valor total plantel:$"+wor.getEquipoPlayer().getValorTotalPlantel());
        Ataque.setText(String.valueOf(wor.getEquipoPlayer().calcularAtaque()));
        Medio.setText(String.valueOf(wor.getEquipoPlayer().calcularMedioCampo()));
        Dfe.setText(String.valueOf(wor.getEquipoPlayer().calcularDefensa()));
        Porte.setText(String.valueOf(wor.getEquipoPlayer().calcularPorteria()));
        Pg.setText(String.valueOf(wor.getEquipoPlayer().EstadisticasLiga.PartidosGanados));
        Pe.setText(String.valueOf(wor.getEquipoPlayer().EstadisticasLiga.PartidosEmpatados));
        Pp.setText(String.valueOf(wor.getEquipoPlayer().EstadisticasLiga.PartidosPerdidos));
        Punt.setText(String.valueOf(wor.getEquipoPlayer().EstadisticasLiga.Puntos));
        Ga.setText(String.valueOf(wor.getEquipoPlayer().EstadisticasLiga.GolesAnotados));
        Ge.setText(String.valueOf(wor.getEquipoPlayer().EstadisticasLiga.GolesEncontra));
        TablaPos.setText("Tabla de posiciones "+wor.getEquipoPlayer().EstadisticasLiga.NombreLigaOTorneo);
        Fondos.setText("Fondos:$"+wor.getEquipoPlayer().Dinero);
        
        
        String AgnoTemporada = wor.Agno+"-"+Integer.valueOf(String.valueOf(wor.Agno+1));
        
        Temp.setText("Temporada "+AgnoTemporada);
        
        
        
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ataque;
    private javax.swing.JButton Avanzar;
    private javax.swing.JLabel Capa;
    private javax.swing.JTextField Dfe;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Fans;
    private javax.swing.JButton Fich;
    private javax.swing.JLabel Fondos;
    private javax.swing.JLabel Forma;
    private javax.swing.JTextField Ga;
    private javax.swing.JTextField Ge;
    private javax.swing.JTextField Medio;
    private javax.swing.JButton Mejoras;
    private javax.swing.JLabel NombreEquipo;
    private javax.swing.JTextField Pe;
    private javax.swing.JTextField Pg;
    private javax.swing.JButton Plantel;
    private javax.swing.JTextField Porte;
    private javax.swing.JTextField Pp;
    private javax.swing.JTextField Punt;
    public javax.swing.JTextArea Results;
    private javax.swing.JButton RetirarJug;
    private javax.swing.JButton RetirarJug1;
    private javax.swing.JButton TablaPos;
    private javax.swing.JLabel Temp;
    private javax.swing.JButton Trofe;
    private javax.swing.JLabel Valor;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
