/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package footballmanager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wesker
 */
public class VistaTabla extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     * @param wor
     * @param LigaSelec
     */
    public VistaTabla(Mundo wor,Liga LigaSelec) {
        initComponents();
        this.wor = wor;
        this.LigaSe = LigaSelec;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Java Football Manager");
 
        this.RenderizarVista();
    }
    
    Equipo Model = null;
    Liga LigaSe = null;
    
    ArrayList<EquiposTableView> EquipesTable = new ArrayList<>();
    
    
    public void Sorting(){
        for (Equipo x : LigaSe.Equipos){
            EquipesTable.add(new EquiposTableView(x.NombreEquipo,x.EstadisticasLiga.PartidosGanados,x.EstadisticasLiga.PartidosPerdidos,x.EstadisticasLiga.PartidosEmpatados,x.EstadisticasLiga.GolesAnotados,x.EstadisticasLiga.GolesEncontra,x.EstadisticasLiga.Puntos));
        }
        Collections.sort(EquipesTable, new Comparator<EquiposTableView>(){
            @Override
            public int compare(EquiposTableView p1, EquiposTableView p2) {
                return Integer.compare(p2.Puntos, p1.Puntos); // Para orden descendente
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NombreEquipo = new javax.swing.JLabel();
        Avanzar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablis = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Equipe = new javax.swing.JTextField();
        Plantel = new javax.swing.JButton();
        Plantel1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Punt = new javax.swing.JTextField();
        Pg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Pp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Pe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Ga = new javax.swing.JTextField();
        Ge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Temp = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Fans = new javax.swing.JLabel();
        Capa = new javax.swing.JLabel();
        Ataque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Medio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Dfe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Porte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Forma = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        NombreEquipo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        NombreEquipo.setForeground(new java.awt.Color(255, 255, 255));
        NombreEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEquipo.setText("jLabel1");

        Avanzar.setBackground(new java.awt.Color(0, 204, 102));
        Avanzar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Avanzar.setForeground(new java.awt.Color(255, 255, 255));
        Avanzar.setText("Volver al menu anterior");
        Avanzar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanzarActionPerformed(evt);
            }
        });

        Tablis.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Tablis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Equipo", "PG", "PP", "PE", "GA", "GC", "Puntos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tablis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tablis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tablis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablisMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablisMousePressed(evt);
            }
        });
        Tablis.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablisPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(Tablis);

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Equipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        Equipe.setEditable(false);
        Equipe.setBackground(new java.awt.Color(0, 204, 102));
        Equipe.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Equipe.setForeground(new java.awt.Color(255, 255, 255));
        Equipe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Equipe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Plantel.setBackground(new java.awt.Color(0, 204, 102));
        Plantel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Plantel.setForeground(new java.awt.Color(255, 255, 255));
        Plantel.setText("Ver plantel");
        Plantel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Plantel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantelActionPerformed(evt);
            }
        });

        Plantel1.setBackground(new java.awt.Color(0, 204, 102));
        Plantel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Plantel1.setForeground(new java.awt.Color(255, 255, 255));
        Plantel1.setText("Vitrina de trofeos");
        Plantel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Plantel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plantel1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "EST. LIGA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Puntos:");

        Punt.setEditable(false);
        Punt.setBackground(new java.awt.Color(153, 255, 153));
        Punt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Punt.setText("0");
        Punt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Pg.setEditable(false);
        Pg.setBackground(new java.awt.Color(153, 255, 153));
        Pg.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pg.setText("0");
        Pg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Partidos ganados:");

        Pp.setEditable(false);
        Pp.setBackground(new java.awt.Color(153, 255, 153));
        Pp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pp.setText("0");
        Pp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Partidos perdidos:");

        Pe.setEditable(false);
        Pe.setBackground(new java.awt.Color(153, 255, 153));
        Pe.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Pe.setText("0");
        Pe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Partidos empatados:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Goles Ant.");

        Ga.setEditable(false);
        Ga.setBackground(new java.awt.Color(153, 255, 153));
        Ga.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ga.setText("0");
        Ga.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Ge.setEditable(false);
        Ge.setBackground(new java.awt.Color(153, 255, 153));
        Ge.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ge.setText("0");
        Ge.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Goles Ec.");

        Temp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Temp.setForeground(new java.awt.Color(255, 255, 255));
        Temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Temp.setText("Temporada 2020-2020");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Temp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Punt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Pg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(Ga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Pp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Ge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Pe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Temp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Punt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "INFORMACIÓN EQUIPO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        Fans.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Fans.setForeground(new java.awt.Color(255, 255, 255));
        Fans.setText("Fans:");

        Capa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Capa.setForeground(new java.awt.Color(255, 255, 255));
        Capa.setText("Cap. Estadio:");

        Ataque.setEditable(false);
        Ataque.setBackground(new java.awt.Color(153, 255, 153));
        Ataque.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Ataque.setText("0");
        Ataque.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ataque:");

        Medio.setEditable(false);
        Medio.setBackground(new java.awt.Color(153, 255, 153));
        Medio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Medio.setText("0");
        Medio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mediocampo:");

        Dfe.setEditable(false);
        Dfe.setBackground(new java.awt.Color(153, 255, 153));
        Dfe.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Dfe.setText("0");
        Dfe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Defensa:");

        Porte.setEditable(false);
        Porte.setBackground(new java.awt.Color(153, 255, 153));
        Porte.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Porte.setText("0");
        Porte.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Porteria:");

        Forma.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Forma.setForeground(new java.awt.Color(255, 255, 255));
        Forma.setText("Formacion:");

        Edad.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Edad.setForeground(new java.awt.Color(255, 255, 255));
        Edad.setText("Edad media:");

        Valor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 255, 255));
        Valor.setText("Valor total del plantel:$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Fans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Capa, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                                    .addComponent(Forma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 38, Short.MAX_VALUE))
                            .addComponent(Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ataque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Medio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Porte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dfe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fans)
                            .addComponent(Ataque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Capa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Forma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Edad))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Medio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Dfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Porte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(Valor)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Equipe)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Plantel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Plantel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Equipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Plantel)
                    .addComponent(Plantel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(NombreEquipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1342, Short.MAX_VALUE)
                    .addComponent(Avanzar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Avanzar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanzarActionPerformed
        // TODO add your handling code here:
        VistaEquipo vivi = new VistaEquipo(wor);
        vivi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AvanzarActionPerformed

    private void TablisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablisMouseClicked
        // TODO add your handling code here:
        if (Tablis.getSelectedRow()!=-1){
            
        
        
        for (Equipo x : LigaSe.Equipos){
            if (x.NombreEquipo.equals(LigaSe.Equipos.get(Tablis.getSelectedRow()).NombreEquipo)){
                Model = x;
            }
        }
        
        
        
        
        Equipe.setText(Model.NombreEquipo);
        Fans.setText("Fans:"+wor.getEquipoPlayer().Fans);
        Capa.setText("Cap. Estadio:"+Model.EstEquipo.Capacidad);
        Forma.setText("Formacion:"+Model.getFormacion());
        Edad.setText("Edad media:"+Model.getEdadMedia());
        Valor.setText("Valor total plantel:$"+Model.getValorTotalPlantel());
        Ataque.setText(String.valueOf(Model.calcularAtaque()));
        Medio.setText(String.valueOf(Model.calcularMedioCampo()));
        Dfe.setText(String.valueOf(Model.calcularDefensa()));
        Porte.setText(String.valueOf((int) Model.calcularPorteria()));
        Pg.setText(String.valueOf(Model.EstadisticasLiga.PartidosGanados));
        Pe.setText(String.valueOf(Model.EstadisticasLiga.PartidosEmpatados));
        Pp.setText(String.valueOf(Model.EstadisticasLiga.PartidosPerdidos));
        Punt.setText(String.valueOf(Model.EstadisticasLiga.Puntos));
        Ga.setText(String.valueOf(Model.EstadisticasLiga.GolesAnotados));
        Ge.setText(String.valueOf(Model.EstadisticasLiga.GolesEncontra));
        }
    }//GEN-LAST:event_TablisMouseClicked

    private void TablisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablisMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablisMousePressed

    private void TablisPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablisPropertyChange

    }//GEN-LAST:event_TablisPropertyChange

    private void PlantelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantelActionPerformed
        // TODO add your handling code here:
        
        if (Model!=null){
            if (!Model.equals(wor.getEquipoPlayer())){
                VistaPlantelOtroEquipo Vistis = new VistaPlantelOtroEquipo (wor,Model,LigaSe);
                Vistis.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, 
                              "No puedes seleccionar tu propio equipo.", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
            }
        }
        
        

        
    }//GEN-LAST:event_PlantelActionPerformed

    private void Plantel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plantel1ActionPerformed
        // TODO add your handling code here:
        if (Model!=null){
            
            
            if (!Model.Trofeos.isEmpty()){
                String Trofies = "";
                
                for (Trofeo x : Model.Trofeos){
                    Trofies+="\n"+x.NombreTrofeo+"\n";
                }
                
                JOptionPane.showMessageDialog(null, 
                              Trofies, 
                              "Trofeos de "+Model.NombreEquipo, 
                              JOptionPane.INFORMATION_MESSAGE);
                
                
            }else{
                JOptionPane.showMessageDialog(null, 
                              "El equipo no posee trofeos.", 
                              "!!!", 
                              JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            
            JOptionPane.showMessageDialog(null, 
                              "No se a seleccionado equipo!", 
                              "!!!", 
                              JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_Plantel1ActionPerformed

    
    
    Mundo wor;


    public void RenderizarVista(){
        
        NombreEquipo.setText(wor.getEquipoPlayer().NombreEquipo);
        
        
        Sorting();
        
        DefaultTableModel modelo = new DefaultTableModel();
       
        modelo.addColumn("Equipo");
        modelo.addColumn("PG");
        modelo.addColumn("PP");
        modelo.addColumn("PE");
        modelo.addColumn("GA");
        modelo.addColumn("GC");
        modelo.addColumn("Puntos");
        
        while (modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        
        for (EquiposTableView ekip : EquipesTable){
            
            Object a[] = new Object[7];
            
            a[0] = ekip.Equipo;
            a[1] = ekip.PG;
            a[2] = ekip.PP;
            a[3] = ekip.PE;
            a[4] = ekip.GA;
            a[5] = ekip.GC;
            a[6] = ekip.Puntos;
            
            modelo.addRow(a);
        }
        
        Tablis.setModel(modelo);
        
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ataque;
    private javax.swing.JButton Avanzar;
    private javax.swing.JLabel Capa;
    private javax.swing.JTextField Dfe;
    private javax.swing.JLabel Edad;
    private javax.swing.JTextField Equipe;
    private javax.swing.JLabel Fans;
    private javax.swing.JLabel Forma;
    private javax.swing.JTextField Ga;
    private javax.swing.JTextField Ge;
    private javax.swing.JTextField Medio;
    private javax.swing.JLabel NombreEquipo;
    private javax.swing.JTextField Pe;
    private javax.swing.JTextField Pg;
    private javax.swing.JButton Plantel;
    private javax.swing.JButton Plantel1;
    private javax.swing.JTextField Porte;
    private javax.swing.JTextField Pp;
    private javax.swing.JTextField Punt;
    private javax.swing.JTable Tablis;
    private javax.swing.JLabel Temp;
    private javax.swing.JLabel Valor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
