/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package footballmanager;

/**
 *
 * @author wesker
 */
public class VistaJugador extends javax.swing.JPanel {

    /**
     * Creates new form VistaJugador
     */
    public VistaJugador() {
        initComponents();
    }
    
    public void Ajustar(Futbolista x){
        NombreJugador2.setText(x.Nombre+" "+x.Apellido);
        Posicion.setText(x.Posicion);
        switch (x.Posicion){
            case "Arquero"->{
                Media.setText(String.valueOf(x.Porteria));
            }
            default ->{
                Media.setText(String.valueOf(x.Media));
            }
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Posicion = new javax.swing.JLabel();
        Media = new javax.swing.JLabel();
        NombreJugador2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Posicion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Posicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Posicion.setText("jLabel1");

        Media.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Media.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Media.setText("jLabel1");

        NombreJugador2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        NombreJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreJugador2.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Posicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Media, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addComponent(NombreJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreJugador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Posicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Media)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Media;
    private javax.swing.JLabel NombreJugador2;
    private javax.swing.JLabel Posicion;
    // End of variables declaration//GEN-END:variables
}
